backend:
  name: github
  repo: Mako923/cartransportreviews
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "companies"
    label: "Companies"
    folder: "companies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Reviews", name: "reviews", widget: "text" }
